version: '3'
services:
  app-db:  
    # Build using Dockerfile in build-db
    build: ./build-db
    container_name: dataspread-db
    expose:
      - "5432"

  app-web:
    # Build using Dockerfile in build-web
    build: ./build-web
    container_name: dataspread-web
    ports:
      # Change left value for different host port i.e. localhost:8080
      - "8080:8080"
    depends_on:
      - app-db

# TODO: Add volumes for db to persist data